services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      - POSTGRES_USER=user-db
      - POSTGRES_PASSWORD=pwd-db
      - POSTGRES_DB=taxi-driver-db
    volumes:
      # Mapping the local directory to the container's data directory
      - ./postgres-data:/var/lib/postgresql/data  
    ports:
      - "5432:5432"
    networks:
      - app-network

  # Define your app service (optional if you want to run your app in Docker as well)
  app:
    build:
      context: .
    ports:
      - "8080:8080"
      - "80:80"
    environment:
      DATABASE_URL: postgres://user-db:pwd-db@db:5432/taxi-driver-db
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
